version: '3.8'

services:
  pgvector-db:
    image: phidata/pgvector:16
    container_name: pgvector_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@pgvector-db:5432/mydatabase
    depends_on:
      - pgvector-db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
