repos:
  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.23.5
    hooks:
    - id: latexindent
      name: LaTeX formatter
      args: [-s, -l, -m]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
