from __future__ import annotations

from enum import Enum


class MainRace(str, Enum):
    HUMAN = "Human"
    ELF = "Elf"
    DWARF = "Dwarf"
    HALFLING = "Halfling"
    HALF_ELF = "Half-Elf"
    HALF_ORC = "Half-Orc"
    TIEFLING = "Tiefling"
    DRAGONBORN = "Dragonborn"
    GNOME = "Gnome"
    AASIMAR = "Aasimar"
    GENASI = "Genasi"
    GOLIATH = "Goliath"
    FIRBOLG = "Firbolg"
    TABAXI = "Tabaxi"
    LIZARDFOLK = "Lizardfolk"
    KENKU = "Kenku"
    TORTLE = "Tortle"
    AARAKOCRA = "Aarakocra"
    BUGBEAR = "Bugbear"
    GOBLIN = "Goblin"
    HOBGOBLIN = "Hobgoblin"
    KOBOLD = "Kobold"
    ORC = "Orc"
    YUAN_TI_PUREBLOOD = "Yuan-ti Pureblood"
    WARFORGED = "Warforged"
    CHANGELING = "Changeling"
    KALASHTAR = "Kalashtar"
    SHIFTER = "Shifter"
    MINOTAUR = "Minotaur"
    CENTAUR = "Centaur"
    SATYR = "Satyr"
    LEONIN = "Leonin"
    LUXODON = "Luxodon"
    VERDAN = "Verdan"
    SIMIC_HYBRID = "Simic Hybrid"
    VEDALKEN = "Vedalken"
    GRUNG = "Grung"
